scheduler:
    _target_: custom_diffusers.continuous_ddpm.ContinuousDDPM
    beta_schedule: linear
    prediction_type: v_prediction
    clip_sample: false
    clip_range:
      - 0
      - null
      
data_dir: /fmi/scratch/project_2001927/nordlin1/emulator_data/
save_dir: ./

# Seed for random number generators
seed: 42
variables: ["TREFHT"]
load_path: /fmi/projappl/project_2001927/nordlin1/papers/CESM_emulatorV2/runs/run_test_aero3_296.pt
gen_mode: gen  # Either gen/val/test
batch_size: 4
sample_steps: 250
start_year: 1850
end_year: 2100
save_name: ssp370_aero_v3 # Only set a save name if you want something special added to your save path
samples_per: 10
cond_file: emissions.nc #emissions.nc
sul_mul: 0
co2_mul: 1
training_mode: "fcn3"   # or "diffusion"
noise_channels: 1     # only used for fcn3
dataset:
  _target_: data.climate_dataset.ClimateDataset
  seq_len: 1

accelerator:
    mixed_precision: bf16

